package io.foldright.ex

import io.foldright.cffu2.Cffu
import io.foldright.cffu2.CompletableFutureUtils
import io.foldright.test_utils.isJava9Plus
import io.foldright.test_utils.java12Plus
import io.foldright.test_utils.testCffuFac
import io.kotest.assertions.throwables.shouldThrowExactly
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldBeEmpty
import io.kotest.matchers.collections.shouldHaveSingleElement
import io.kotest.matchers.shouldBe
import java.util.concurrent.CompletableFuture
import java.util.concurrent.ExecutionException

/**
 * @see ExTest.test_addSuppressed_not_allowed_add_self
 */
class ExceptionReportionSafetyTest : FunSpec({
    ////////////////////////////////////////////////////////////////////////////////
    // CompletableFuture
    ////////////////////////////////////////////////////////////////////////////////

    test("üëé CF.exceptionally() swallows original exceptionÔ∏è") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionally")

        val cf: CompletableFuture<Int> = CompletableFutureUtils.failedFuture<Int>(original)
            .exceptionally { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        // the exception is swallowed! üëé
        original.suppressed.shouldBeEmpty()
        new.suppressed.shouldBeEmpty()
    }

    test("üëé CF.exceptionallyAsync() swallows original exceptionÔ∏è").config(enabledIf = java12Plus) {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionallyAsync")

        val cf: CompletableFuture<Int> = CompletableFutureUtils.failedFuture<Int>(original)
            .exceptionallyAsync { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        // the exception is swallowed! üëé
        original.suppressed.shouldBeEmpty()
        new.suppressed.shouldBeEmpty()
    }

    test("üëé CF.exceptionallyCompose() swallows original exceptionÔ∏è").config(enabledIf = java12Plus) {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionallyCompose")

        val cf: CompletableFuture<Int> = CompletableFutureUtils.failedFuture<Int>(original)
            .exceptionallyCompose { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        // the exception is swallowed! üëé
        original.suppressed.shouldBeEmpty()
        new.suppressed.shouldBeEmpty()
    }

    test("üëé CF.exceptionallyComposeAsync() swallows original exceptionÔ∏è").config(enabledIf = java12Plus) {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionallyComposeAsync")

        val cf: CompletableFuture<Int> = CompletableFutureUtils.failedFuture<Int>(original)
            .exceptionallyComposeAsync { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        // the exception is swallowed! üëé
        original.suppressed.shouldBeEmpty()
        new.suppressed.shouldBeEmpty()
    }

    test("üëé CF.handle() swallows original exception") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("handle")

        val cf: CompletableFuture<Int> = CompletableFutureUtils.failedFuture<Int>(original)
            .handle { _, _ -> throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        // the exception is swallowed! üëé
        original.suppressed.shouldBeEmpty()
        new.suppressed.shouldBeEmpty()
    }

    test("üëé CF.handleAsync() swallows original exception") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("handleAsync")

        val cf: CompletableFuture<Int> = CompletableFutureUtils.failedFuture<Int>(original)
            .handleAsync { _, _ -> throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        // the exception is swallowed! üëé
        original.suppressed.shouldBeEmpty()
        new.suppressed.shouldBeEmpty()
    }

    test("üëç CF.whenComplete() does not swallow new exception for Java 9+") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("whenComplete")

        val cf: CompletableFuture<Int> = CompletableFutureUtils.failedFuture<Int>(original)
            .whenComplete { _, _ -> throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe original
        // the new exception is not swallowed! üëç
        if (isJava9Plus()) original.suppressed.shouldHaveSingleElement(new)
        // the new exception is swallowed in Java 8! üëé
        else original.suppressed.shouldBeEmpty()
        new.suppressed.shouldBeEmpty()
    }

    test("üëç CF.whenCompleteAsync() does not swallow new exception for Java 9+") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("whenCompleteAsync")

        val cf: CompletableFuture<Int> = CompletableFutureUtils.failedFuture<Int>(original)
            .whenCompleteAsync { _, _ -> throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe original
        // the new exception is not swallowed! üëç
        if (isJava9Plus()) original.suppressed.shouldHaveSingleElement(new)
        // the new exception is swallowed in Java 8! üëé
        else original.suppressed.shouldBeEmpty()
        new.suppressed.shouldBeEmpty()
    }

    ////////////////////////////////////////////////////////////////////////////////
    // Cffu
    ////////////////////////////////////////////////////////////////////////////////

    test("üëç Cffu.catching() does not swallow original exceptionÔ∏è") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionally")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .catching(RuntimeException::class.java) { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.catchingAsync() does not swallow original exceptionÔ∏è") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionallyAsync")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .catchingAsync(RuntimeException::class.java) { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.exceptionally() does not swallow original exceptionÔ∏è") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionally")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .exceptionally { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.exceptionallyAsync() does not swallow original exceptionÔ∏è") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionallyAsync")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .exceptionallyAsync { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.catchingCompose() does not swallow original exceptionÔ∏è") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionallyCompose")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .catchingCompose(RuntimeException::class.java) { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.catchingComposeAsync() does not swallow original exceptionÔ∏è") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionallyComposeAsync")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .catchingComposeAsync(RuntimeException::class.java) { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.exceptionallyCompose() does not swallow original exceptionÔ∏è") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionallyCompose")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .exceptionallyCompose { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.exceptionallyComposeAsync() does not swallow original exceptionÔ∏è") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("exceptionallyComposeAsync")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .exceptionallyComposeAsync { throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.handle() does not swallow original exception") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("handle")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .handle { _, _ -> throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.handleAsync() does not swallow original exception") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("handleAsync")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .handleAsync { _, _ -> throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe new
        original.suppressed.shouldBeEmpty()
        // the original exception is not swallow üëç
        new.suppressed.shouldHaveSingleElement(original)
    }

    test("üëç Cffu.whenComplete() does not swallow new exception") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("whenComplete")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .whenComplete { _, _ -> throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe original
        // the new exception is not swallowed! üëç
        original.suppressed.shouldHaveSingleElement(new)
        new.suppressed.shouldBeEmpty()
    }

    test("üëç Cffu.whenCompleteAsync() does not swallow new exception") {
        val original = RuntimeException("Bang")
        val new = RuntimeException("whenCompleteAsync")

        val cf: Cffu<Int> = testCffuFac.failedFuture<Int>(original)
            .whenCompleteAsync { _, _ -> throw new }

        val ee = shouldThrowExactly<ExecutionException> { cf.get() }
        ee.suppressed.shouldBeEmpty()
        ee.suppressed.shouldBeEmpty()

        ee.cause shouldBe original
        // the new exception is not swallowed! üëç
        original.suppressed.shouldHaveSingleElement(new)
        new.suppressed.shouldBeEmpty()
    }
})
